### ISSUE TITLE
Migrate Pandoc Reader improvements

### ISSUE THREAD

**Issue by justinmayer** [pelican-plugins/pandoc-reader#1]
This issue tracks the gradual migration of @nandac's improvements to the Pandoc Reader plugin.

**Comment by justinmayer** [comment]
@nandac: As we discussed on IRC, please submit your changes gradually by creating new branches and pushing them one at a time to this repository, and then create pull request from those branches, which will eventually be merged to `main`. Rather than a flood all at once, perhaps start with one or two branches + pull requests until we establish a rhythm. Looking forward to collaborating! 😁

**Comment by nandac** [comment]
@justinmayer I have added a single PR at: https://github.com/pelican-plugins/pandoc-reader/pull/3

Kindly let me know if it is okay for me to merge PRs or if they should go through a review process first.

I would prefer it if someone could review just to get a second pair of eyes.

**Comment by justinmayer** [comment]
I agree — having a second pair of eyes is often useful. I'll review tomorrow so we can iterate on this further. 😊

**Comment by nandac** [comment]
Closing this issue as the plugin has been migrated.
