### ISSUE TITLE
Request to be added as a maintainer on PyPI

### ISSUE THREAD

**Issue by nandac** [pelican-plugins/pandoc-reader#14]
@justinmayer Thank you for publishing the plugin.

Could you please add me as a maintainer for this project in PyPI?

I did not have an account on PyPI before but have one now.

The user name is nandac.

Thanks.

**Comment by justinmayer** [comment]
Hi Nanda. I sent you an invitation. Please keep in mind, however, that the idea is to **avoid direct publishing to PyPI**. Rather, the intention is to publish automatically (as was just done a short while ago for v1.0.0) via appropriate `RELEASE.md` files, as noted in the relevant [Pelican core documentation](https://docs.getpelican.com/en/stable/contribute.html#using-git-and-github).

In short, each and every future pull request (regardless of origin) should ideally include such a `RELEASE.md` file (usually with `Release type: patch`), which will subsequently auto-publish `1.0.1`, `1.0.2`, et cetera. Make sense?

**Comment by nandac** [comment]
@justinmayer Yes, I understand. I will not be publishing directly to PyPI and break the CI/CD process. I know how much of a headache that can cause.

**Comment by justinmayer** [comment]
Absolutely! A pleasure to collaborate with you. 😁
