### ISSUE TITLE
Empty values break `CONTENT_CACHING_LAYER = "reader"`

### ISSUE THREAD

**Issue by reagle** [pelican-plugins/pandoc-reader#15]
When used with caching, an empty value in metadata causes the following exception: `CRITICAL: 'object' object is not iterable` when the layer is set to `reader`. It doesn't seem to have the same problem with generator.

```
---
author: Joseph Reagle
category: praxis
date: '2013-12-02'
tags: ''
title: Archiving sources
...

Later this week I'll be participating on a panel of the [New Media in American Literary History Interdisciplinary Symposium](http://www.northeastern.edu/nulab/nmalh/). I plan to [talk](https://reagle.org/joseph/talks/2013/12-bib-bitrot.html) about bibliography and bitrot.
```

**Comment by avaris** [comment]
This appears to be a `pelican` bug and will be fixed there (see getpelican/pelican#2825). So, I'm closing this one here.
