### ISSUE TITLE
Publish new release to PyPI

### ISSUE THREAD

**Issue by justinmayer** [pelican-plugins/pandoc-reader#2]
Once the migration of new improvements in #1 has been completed, the next step is to publish a new release of the modernized plugin to PyPI.

In order to do that, we will need the assistance of @ErwinJanssen, who has already published a package with the same name to PyPI in the past.

**Comment by justinmayer** [comment]
@ErwinJanssen: Would you be willing to add the [`pelicanteam`](https://pypi.org/user/pelicanteam/) PyPI account with `Owner` role to the existing [pelican-pandoc-reader](https://pypi.org/project/pelican-pandoc-reader/) project on PyPI? That would allow us to publish a new modernized version of this plugin. Of course, you are most welcome to join us here and participate in the plugin's future development. Cheers, and many thanks in advance for your help! 😁

**Comment by justinmayer** [comment]
Hi @ErwinJanssen. I just looked at your Pelican-powered site, which is great. I especially like how you handled the light/dark-mode switching. Well done! 🌞 🌚  

I also wanted to follow up regarding the [pelican-pandoc-reader](https://pypi.org/project/pelican-pandoc-reader/) project on PyPI. We could of course publish under a different name, but I think end users would be best served by unifying our efforts under a single banner and thereby eliminating any potential confusion. What do you say?

**Comment by ErwinJanssen** [comment]
Hi @justinmayer! The move from a monolithic repository to separate packages sounds like a great idea, and of course I would love to help. I have added `pelicanteam` as an owner to the project on PyPi, so you can publish a new version of this plugin :smile:

> I just looked at your Pelican-powered site, which is great. I especially like how you handled the light/dark-mode switching. Well done! :sun_with_face: :new_moon_with_face:

Thanks! :sunglasses:

About the plugin itself, your README says that only flat metadata fields are supported. Maybe it's on the roadmap already, but in my version I delegated reading the metadata to Pandoc itself. It's not the most elegant solution, but it ensures that Pelican and Pandoc both use the same metadata fields, [link to the code here](https://github.com/ErwinJanssen/pelican-pandoc-reader/blob/4ab9fb1fc78d86d4074fa55b9dcf41c50e8bcbfb/src/pelican_pandoc_reader/__init__.py#L46).

**Comment by nandac** [comment]
@ErwinJanssen Thank you for your response and for adding the pelicanteam as an owner.

I was not completely happy with the metadata processing capabilities of the plugin in its present status, and would definitely like to incorporate your solution and test it out, which is indeed more elegant.

**Comment by nandac** [comment]
@ErwinJanssen  I have thanks to the code snippet you had pointed in your code I have incorporated it into my code and as for as my testing is concerned it works really well. 

The pull request is available here: https://github.com/pelican-plugins/pandoc-reader/pull/6

Perhaps you and @justinmayer could review and merge.

**Comment by ErwinJanssen** [comment]
Good to hear, glad I could be of help!

**Comment by nandac** [comment]
@justinmayer After having the commit I made yesterday merged I think we could make a release to PyPI.

**Comment by justinmayer** [comment]
@nandac: Agreed. Would you mind putting together a list of bullet points for the change-log and posting them as a comment here?

**Comment by nandac** [comment]
I have one more minor commit that I posted just a few minutes ago.

As far as the changelog is concerned would the commit message be sufficient?

My main question is if there is a standard we should follow.

**Comment by justinmayer** [comment]
Commit history tends to be noisier than most users care about. Folks who want to see details such as code style, CI/CD, and tests are usually better served by looking at the commit stream itself. I think that the purpose of the change-log is for end-users to be able to understand — from a high level — what has changed.

To that end, I propose:

* Convert to namespace plugin
* Add support for citations, table of contents generation, and reading time calculation
* Add support for Pandoc default files
* Add support for specifying `citeproc` as a filter

Anything important enough to mention that's not on the above list?

**Comment by nandac** [comment]
@justinmayer I think what you have proposed is good and captures the main features.

**Comment by justinmayer** [comment]
[Pandoc Reader 1.0.0](https://github.com/pelican-plugins/pandoc-reader/releases/tag/1.0.0) has been released. Many thanks to Nanda and Erwin for all the work on this! 🎉
