### ISSUE TITLE
Cannot use with `uv tool install pelican`

### ISSUE THREAD

**Issue by reagle** [pelican-plugins/pandoc-reader#41]
Hi, I thought I'd trying  [uv](https://github.com/astral-sh/uv) this weekend and tried installing pelican this with `uv tool install pelican --with pelican-pandoc-reader` but I end up getting markdown reader issues:

```
WARNING  praxis/teaching/citing-wikipedia.md: Could not import           readers.py:687
     'markdown.Markdown'. Have you installed the 'markdown' package?
```

Has anyone with more clue/experience tried pelican with uv?

**Comment by nandac** [comment]
@reagle I cannot say that I have encountered this problem and have not used uv before.

The error may be an issue with Pelican and not with the plugin per se, perhaps something has changed.

Does installing the normal way through pip also have the same issue?

I will need some time to investigate what is going on. Thank you for opening the issue.

**Comment by reagle** [comment]
It looks like this works: `uv tool install pelican --with pelican-pandoc-reader --with markdown` . It looks like you are using poetry whereas uv uses PEP 621, so uv isn't seeing all the dependencies.
